[package]
name = "nix-transform-el"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
emacs-module = {path = "../emacs-module"}
nix-transform = {path = "../nix-transform"}